#include "led.h"

void led_init() {
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	MODIFY_REG(GPIOA->CRL, GPIO_CRL_MODE5 | GPIO_CRL_CNF5, 
		   GPIO_CRL_MODE5_1);
}

void led_on() {
	GPIOA->ODR |= GPIO_ODR_ODR5;
}

void led_off() {
	GPIOA->ODR &= ~GPIO_ODR_ODR5;
}

void led_switch() {
	GPIOA->ODR ^= GPIO_ODR_ODR5;
}

void RGBled_init() {
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;	
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;

	// mode = alternate funtion
	MODIFY_REG(GPIOA->CRL,
	GPIO_CRL_CNF0 | GPIO_CRL_MODE0 | GPIO_CRL_CNF1 | GPIO_CRL_MODE1
	| GPIO_CRL_CNF2 | GPIO_CRL_MODE2,
	GPIO_CRL_CNF0_1 | GPIO_CRL_MODE0_1 | GPIO_CRL_CNF1_1 | GPIO_CRL_MODE1_1
	| GPIO_CRL_CNF2_1 | GPIO_CRL_MODE2_1);

	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	TIM2->PSC = 0;
	TIM2->ARR = 255;
	TIM2->CCR1 = 0; // blue
	TIM2->CCR2 = 0; // green
	TIM2->CCR3 = 0; // red
	CLEAR_BIT(TIM2->CCMR1, TIM_CCMR1_CC1S | TIM_CCMR1_CC2S);
	CLEAR_BIT(TIM2->CCMR2, TIM_CCMR2_CC3S);
	SET_BIT(TIM2->CCMR1, 0x6 << TIM_CCMR1_OC1M_Pos | 0x6 << TIM_CCMR1_OC2M_Pos);
	SET_BIT(TIM2->CCMR2, 0x6 << TIM_CCMR2_OC3M_Pos);
	SET_BIT(TIM2->CCMR1, TIM_CCMR1_OC1PE | TIM_CCMR1_OC2PE);
	SET_BIT(TIM2->CCMR2, TIM_CCMR2_OC3PE);
	TIM2->CR1 |= TIM_CR1_ARPE;
	TIM2->EGR |= TIM_EGR_UG;
	TIM2->CR1 |= TIM_CR1_CEN;
	SET_BIT(TIM2->CCER, TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E
		| TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E);
}

void RGBled_set(unsigned char r, unsigned char g, unsigned char b) {
	TIM2->CCR1 = b;
	TIM2->CCR2 = g;
	TIM2->CCR3 = r;
}

